### ISSUE TITLE
Validator: incorrect value scope error

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#102]
Refer to **AIX nmon WLM** portal.

1. Error messages are similar, it seems that the same checks are performed in different places:
     ![Selection_001](https://user-images.githubusercontent.com/20650874/68315662-25279900-00c9-11ea-98a2-50dd4243da4b.png)

2. Error is incorrect, because setting is placed in `[group]` section, widget type is unknown.

**Comment by PolinaShneider** [comment]
Took a look at the config and I suggest we should do the following:

1) When `[widget]` is finished and section having **smaller** depth (for instance, group) started, we should set `this.currentWidget` to `null|undefined`, which is not done now
2) You are right — similar checks are performed in various parts of validator. It's checked in [validator.ts](https://github.com/axibase/charts-language-service/blob/master/src/validator.ts#L1017) itself and in [noUselessSettings rules](https://github.com/axibase/charts-language-service/blob/master/src/relatedSettingsRules/presenceValidation/noUselessSettings/index.ts#L23) too. We need to inspect our validation logic, and probably leave these checks only in rules and remove them from `validator.ts`
