### ISSUE TITLE
Validator: improve position validation

### ISSUE THREAD

**Issue by PolinaShneider** [axibase/charts-language-service#112]
If `position` is specified, `width-units` and `height-units` aren't useless, because `position` setting from now will define coordinates of top left widget corner

**P.S.** Just remove [this](https://github.com/axibase/charts-language-service/blob/master/src/relatedSettingsRules/presenceValidation/noUselessSettings/widgetsDimensions.ts#L23) rule when charts visual constructor is fully implemented

![image](https://user-images.githubusercontent.com/15448200/69437525-8b145180-0d54-11ea-9ec3-ec4d83e45f04.png)

**Comment by annstriganova** [comment]
@rodionos, is it still actual? It seems that `position` overrides `width-units`:
![Selection_001](https://user-images.githubusercontent.com/20650874/73381122-48cc3b00-42d6-11ea-8650-5fd74ba00933.png)

https://apps.axibase.com/chartlab/1b677aa7/6/

**Comment by rodionos** [comment]
Please check with Alex V
