### ISSUE TITLE
Formatting: increase indent in script block with broken JS

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#15]
Script block with broken JS is not formatted, is it possible to increase indent inside block?

Actual:

```js
script
window.function () {
};
endscript
```
Expected:

```js
script
  window.function () {
  };
endscript
```

**Comment by PolinaShneider** [comment]
Yes, adding specified base indent it's possible. However it will also affect correctly formatted, but syntactically incorrect script.

![invalid-js-formatting](https://user-images.githubusercontent.com/15448200/63598907-2caacc00-c5c9-11e9-9256-1f8cd7d2378b.gif)

**Comment by annstriganova** [comment]
@PolinaShneider, please, implement.
