### ISSUE TITLE
Validator: wrong alert on known setting

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#23]
![Selection_001](https://user-images.githubusercontent.com/20650874/63533090-c6647180-c514-11e9-921f-74717a015ead.png)

https://apps.axibase.com/chartlab/7c05786f/5/

**Comment by PolinaShneider** [comment]
@annstriganova, did I correctly understand that the problem is error message range?
It should show like this (`test` alias instead of `value` alias) ⤵️

![image](https://user-images.githubusercontent.com/15448200/64953256-0d7f2180-d88b-11e9-941e-de6f87c1e879.png)

**Comment by annstriganova** [comment]
Yes, it seems so, range is need to be fixed.
