### ISSUE TITLE
column settings validation for collapsible and summary-text settings

### ISSUE THREAD

**Issue by rodionos** [axibase/charts-language-service#36]
These settings are allowed.

https://axibase.com/docs/charts/widgets/alert-table/#collapsible

https://apps.axibase.com/chartlab/66c7f3f5

**Comment by PolinaShneider** [comment]
@rodionos this is already resolved by #33. I will update chartlab

**Comment by PolinaShneider** [comment]
Updated chartlab. If the problem was fixed, I think, the issue could be closed
