### ISSUE TITLE
Formatter: multiple issues in `for` loop

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#41]
1. Extra blank line is not deleted.
2. Wrong indent for several subsequent `for` loops.
![Selection_001](https://user-images.githubusercontent.com/20650874/64046585-e16a5d80-cb74-11e9-93a2-9e00736f2964.png)

https://apps.axibase.com/chartlab/42a161bc/12/

**Comment by PolinaShneider** [comment]
What behaviour do we want for nested sections in `for` loop? https://apps.axibase.com/chartlab/677f2f05

**Comment by PolinaShneider** [comment]
I mean, do we want to preserve blank lines between nested sections and remove blank line only before **first** section in control keyword construction? 

Or do we want to get rid of all sections separators inside control constructions?

**Comment by PolinaShneider** [comment]
@annstriganova please check, if issue with subsequent for loops indents is still present for you. Updated chartlab with latest [PR](https://github.com/axibase/charts-language-service/pull/43), reverting `[column]` handling logic, and indents seem to work as expected.

Blank lines will fix soon.

**Comment by annstriganova** [comment]
> 2. Wrong indent for several subsequent `for` loops.

Is not reproduced.

I suggest the following formatting behavior:
![Selection_001](https://user-images.githubusercontent.com/20650874/64338700-13ebde80-cfeb-11e9-959e-42bcd3b5d857.png)

1. No blank line after `for` declaration.
2. Blank line before `for` declaration.
3. If `for` declared inside `[configuration]`, `[group]`, `[widget]`, align as section setting.
4. Preserve blank lines between sections inside `for`.
![Selection_002](https://user-images.githubusercontent.com/20650874/64339445-c1abbd00-cfec-11e9-9c83-a3c62c9e30f8.png)
5. In sections with depth > `[widget]`, align to parent widget.

@rodionos, could you review, please, will it be convenient for user?
