### ISSUE TITLE
Validator: check each item of `multiple` setting list

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#52]
- [ ] Review Charts [docs](https://axibase.com/docs/charts/) and find particular use-cases, when check of each list item is useful.
- [ ] Split `multiple` setting into items and call [`checkType`](https://github.com/axibase/charts-language-service/blob/fc5ad37c7e6c252bb42f13e947f07dd1f53f4f83/src/setting.ts#L49) on each one.

**Comment by PolinaShneider** [comment]
How it would be convenient to show diagnostic? I mean diagnostic range
1. At every incorrect item of list
2. At entire setting, which represents a list?
