### ISSUE TITLE
Validator: multiline `var` handling is broken

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#58]
If `[` is placed at the next line, wrong alert is raised:

![Selection_001](https://user-images.githubusercontent.com/20650874/64611383-f9927600-d3d9-11e9-84ac-f3f7f61ce30e.png)

```elm
var bmcs =
  [
  "b_idx_above",
  "b_tail_below",
  "b_valmin",
  "b_win_greater"
  ]
endvar
```

**Comment by PolinaShneider** [comment]
@annstriganova multiline `var` with bracket at the **same** line as equal sign works fine. This will give no error. 

```
var bmcs = [
  "b_idx_above",
  "b_tail_below",
  "b_valmin",
  "b_win_greater"
]
endvar
```

Do we want both bracket same line and next line syntax support?

**Comment by PolinaShneider** [comment]
BTW, it's quite easy to fix. But will we need same support for some other keywords. If so, it might be good idea to expand API
