### ISSUE TITLE
Formatter: wrong indent increment in multi line comments

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#78]
![screenscast_20190925_154005](https://user-images.githubusercontent.com/20650874/65601459-cb509100-dfaa-11e9-937a-ebc662ea240b.gif)

```ts
/*
 Open dialog widget only on confirm.
 */
```

**Comment by PolinaShneider** [comment]
Can you provide a link to example? Cannot reproduce locally

**Comment by annstriganova** [comment]
https://apps.axibase.com/chartlab/17d4321e/3/
