### ISSUE TITLE
Validator: implement `sort` check

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/charts-language-service#89]
Currently `sort` setting is validated only by type. That's why anything can be written there: [incorrect time unit](https://apps.axibase.com/chartlab/9a0dd4c6/14/) or [incorrect value](https://apps.axibase.com/chartlab/9a0dd4c6/85/)
Add validation for `sort` setting

**Comment by annstriganova** [comment]
General syntax:

```ls
sort = sort_value_1 SORT_ORDER, sort_value_2 SORT_ORDER
```
* `sort_value` is optional, i.e. `sort = ASC` is allowed, in this case `sort_value = value` by default.
* `SORT_ORDER` is optional and may be in any case: `/^(asc|(desc))(ending)?$/i`, default sort order is `ASC`, i.e  `sort = cpu_busy` is valid

Refer to specific syntax for:
* [Calendar](https://axibase.com/docs/charts/widgets/calendar-chart/#sort)
* [Table](https://axibase.com/docs/charts/widgets/shared-table/#sort)
* [Bar](https://axibase.com/docs/charts/widgets/bar-chart/#sort)
